# Generated by Django 2.0.6 on 2018-06-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180612_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergik',
            fields=[
                ('id_alergik', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('PatientName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
            ],
            options={
                'db_table': 't_alergik',
            },
        ),
        migrations.CreateModel(
            name='Chronicdisease',
            fields=[
                ('id_chronic_disease', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('PatientName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
            ],
            options={
                'db_table': 't_chronic_disease',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id_operation', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField(default=None)),
                ('PatientName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
            ],
            options={
                'db_table': 't_operation',
            },
        ),
    ]
