# Generated by Django 2.0.6 on 2018-06-12 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_doctor_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patienthistory',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('Diag', models.CharField(max_length=100)),
                ('Epicris', models.TextField(default=None)),
                ('Login', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_history',
            },
        ),
    ]
