# Generated by Django 2.0.6 on 2018-06-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_patienthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='Login',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Patient'),
        ),
    ]
