# Generated by Django 2.0.6 on 2018-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id_day', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_week_days',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id_disease', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 't_disease',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id_medicine', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_medicine',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id_procedure', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 't_procedure',
            },
        ),
    ]
