# Generated by Django 2.0.6 on 2018-06-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dict', '0002_blood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graft',
            fields=[
                ('id_graft', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=30)),
                ('Patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
            ],
            options={
                'db_table': 't_graft',
            },
        ),
    ]
