# Generated by Django 2.0.6 on 2018-06-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_graft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graft',
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Graft',
        ),
    ]
