# Generated by Django 2.0.6 on 2018-06-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id_r', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
                ('Patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
            ],
            options={
                'db_table': 't_reception',
            },
        ),
    ]
